## Numerical Python(Numpy) - Part1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np


In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [4]:
b = np.array([1,2,3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional Array

In [5]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype, a.shape

(dtype('float64'), (4,))

## 2. Array shape

In [10]:
# Vector(1차원)
vector = np.array([1,4,5,8])
vector.shape

(4,)

In [12]:
# Matrix(2차원)
matrix = np.array([[1,2,3], [4,5,16]])
print(matrix.shape)
print(matrix)

(2, 3)
[[ 1  2  3]
 [ 4  5 16]]


In [13]:
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [15]:
# 1차원 : (4,) 2차원 : (2,3) 3차원 : (2,3,4)
tensor.shape

(2, 3, 4)

In [16]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [17]:
# element의 개수
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [20]:
# data type
# float32: 32bit 표시 - single precision
# float64: 64bit 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

## 3. reshape

In [22]:
matrix.shape

(2, 3)

In [23]:
matrix.reshape(6,)

array([ 1,  2,  3,  4,  5, 16])

In [24]:
matrix.reshape(3,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5, 16]])

In [25]:
# -1은 numpy가 알아서 맞춰줌 (단, size가 동일)
matrix.reshape(-1,)

array([ 1,  2,  3,  4,  5, 16])

In [27]:
matrix.reshape(3,-1).shape
matrix

array([[ 1,  2,  3],
       [ 4,  5, 16]])

In [28]:
matrix.reshape(3,-1).shape

(3, 2)

In [30]:
tensor.reshape(4,-1).shape

(4, 6)

In [36]:
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [32]:
# 1차원
matrix.reshape(-1,)

array([ 1,  2,  3,  4,  5, 16])

In [34]:
# 2차원
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5, 16]])

In [35]:
matrix.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [16]])

## flatten

In [37]:
tensor.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [39]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 4. Indexing & Slicing

### Indexing

In [40]:
matrix

array([[ 1,  2,  3],
       [ 4,  5, 16]])

In [43]:
matrix.shape

(2, 3)

In [41]:
matrix[0][1]

2

In [42]:
matrix[0,1]

2

In [46]:
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [52]:
tensor.shape

(2, 3, 4)

In [45]:
tensor[1,1,2]

19

## Slicing

In [47]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
b.shape

(4, 4)

In [48]:
# 5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [50]:
# 5,6,7, 9,10,11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [51]:
# 1,3,9,11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [58]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [59]:
c.shape

(3,)

In [53]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
# X는 앞에 3열, y는 마지막 열
X, y = b[:, :-1], b[:, -1]
X.shape, y.shape

((4, 3), (4,))

In [55]:
y

array([ 3,  7, 11, 15])

In [56]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])