In [ ]:
8 & 1

0

### 1. 행렬 만들기

###1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오
###10 20 30 40
###50 60 70 80

In [2]:
import numpy as np

In [ ]:
np.array([10,20,30,40,50,60,70,80]).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
np.arange(1,9).reshape(2,4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

###  2. 인덱싱, 슬라이싱

###다음 행렬과 같은 행렬이 있다
###m =
###np.array ([[ 0, 1, 2, 3,4]
###           [ 5, 6, 7, 8, 9],
###          [10, 11, 12, 13, 14]])
1)
이 행렬에서 값 7 을 인덱싱한다
2)
이 행렬에서 값 14 을 인덱싱한다
3)
이 행렬에서 배열 [6, 7] 을 슬라이싱한다
4)
이 행렬에서 배열 [7, 12] 을 슬라이싱한다
5)
이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다

In [ ]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a[1][2]

7

In [ ]:
a[2][4]

14

In [ ]:
a[1][1:3]

array([6, 7])

In [ ]:
a[1,1:3]

array([6, 7])

In [ ]:
a[1:,2]


array([ 7, 12])

In [ ]:
a[:2, 3:]

array([[3, 4],
       [8, 9]])

### Boolean indexing

In [ ]:
f = a.flatten()

In [ ]:
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [ ]:
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [ ]:
f[np.logical_and(f%3==0, f%4==1)]

array([9])

### 4. eye로 행렬 만들기

In [ ]:
np.eye(5,5,k=-1)*3 + np.eye(5,5)*2 + np.eye(5,5,k=1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### Matrix operation

In [ ]:
np.random.seed(2021)
m = np.random.uniform(0,10,30).reshape(5,6).round(4)
m

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [ ]:
np.max(m)

9.9724

In [ ]:
np.sum(m, axis =1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [ ]:
np.max(m, axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [ ]:
np.mean(m, axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [ ]:
np.min(m, axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

### 6. Sorting

In [13]:
score = np.array([[1,2,3,4], [46,99,100,71], [81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [14]:
np.sort(score)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [15]:
# 2행을 정렬 :  46 71 99 100, array[인덱스값]
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [19]:
# 내림차순
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### 7. 주사위 100번

In [ ]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

### 8.가격이 10,000 원인 주식이 있다 . 이 주식의 일간 수익률 은 기댓값이 0% 이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자 . 250 일 동안의 주가를 무작위로 생성하시오

In [ ]:
np.mean(dice)

3.7

In [ ]:
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [10]:
np.random.seed(2021)
price = 10000
rate = np.random.normal(0,0.1,10)
for i in range(10):
  price = price + np.round(price * rate[i])
  print(int(price), end=',')

11489,12266,11753,10805,11406,10601,11800,12561,12695,13231,

In [11]:
# 250개
np.random.seed(2021)
price_list = []
rate = np.random.normal(0,0.1,250)
price = 10000
for i in range(250):
  price += np.round(price * rate[i])
  price_list.append(int(price))

In [12]:
price_list[:10]

[11489, 12266, 11753, 10805, 11406, 10601, 11800, 12561, 12695, 13231]